// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjoamnvuleqfwqknatln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqb2FtbnZ1bGVxZndxa25hdGxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxOTQ0NjYsImV4cCI6MjA2MTc3MDQ2Nn0.u1R6Nfs1toc7nxNnbd1p9qBR-Y8oTRt-qsx8i79r91M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);